import { StyleSheet } from "react-native";

// Modificar según necesidad
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    justifyContent: "center",
  },
}); export const gameDetailScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
    gap: 16,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E5E7EB",
    borderRadius: 12,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  row: {
    borderTopColor: "#F3F4F6",
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 12,
  },
  label: {
    color: "#6B7280",
    fontSize: 14,
    fontWeight: "600",
  },
  value: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "600",
  },
  backButton: {
    backgroundColor: "#E5E7EB",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    marginTop: 16,
  },
  backButtonText: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "600",
  },
});

export const gameFormScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
    gap: 16,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
  },
  fieldGroup: {
    gap: 6,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
  },
  input: {
    borderColor: "#c5cbd3",
    borderRadius: 8,
    borderWidth: 1,
    fontSize: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inputError: {
    borderColor: "#d92d20",
  },
  dateText: {
    color: "#111827",
    fontSize: 16,
  },
  roleSelectContainer: {
    borderColor: "#c5cbd3",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    padding: 8,
  },
  roleOption: {
    borderColor: "#c5cbd3",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  roleOptionSelected: {
    backgroundColor: "#0b5fff",
    borderColor: "#0b5fff",
  },
  roleOptionText: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "600",
  },
  roleOptionTextSelected: {
    color: "#ffffff",
  },
  errorText: {
    color: "#d92d20",
    fontSize: 12,
  },
  actions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  passwordActions: {
    flexDirection: "row",
    gap: 8,
  },
  inlineSecondaryButton: {
    alignItems: "center",
    borderColor: "#c5cbd3",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 10,
  },
  inlineSecondaryButtonText: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "600",
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: "#c5cbd3",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 12,
  },
  scoreInput: {
    borderBottomWidth: 1,
    borderBottomColor: "#D1D5DB",
    paddingVertical: 4,
    fontSize: 16,
    color: "#1F2937",
    textAlign: "center",
    width: 60,
  },
  secondaryButtonText: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "600",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#0b5fff",
    borderRadius: 8,
    flex: 1,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  disabledButton: {
    backgroundColor: "#7aa8ff",
  },
});

export const gameListScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  headerRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
  },
  createButton: {
    backgroundColor: "#0b5fff",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  createButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  listContainer: {
    flexGrow: 1,
    gap: 12,
    paddingBottom: 16,
  },
  emptyState: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingVertical: 32,
  },
  emptyStateText: {
    color: "#6B7280",
    fontSize: 14,
    marginTop: 8,
    textAlign: "center",
  },
  card: {
    alignItems: "flex-start",
    backgroundColor: "#FFFFFF",
    borderColor: "#E5E7EB",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 14,
  },
  cardActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 8,
    width: "20%",
  },
  gameInfoColumn: {
    alignItems: "center",
    justifyContent: "center",
    width: "80%",
  },
  gameHeader: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  gameScoreText: {
    color: "#4B5563",
    fontSize: 14,
    marginTop: 4,
    textAlign: "center",
    textAlignVertical: "center",
    flexWrap: "wrap",
    flexShrink: 1,
  },
  gamePeriodsText: {
    color: "#6B7280",
    fontSize: 12,
    marginTop: 2,
    textAlign: "center",
  },
  editButton: {
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#d1d5db",
    borderRadius: 8,
    borderWidth: 1,
    padding: 8,
  },
  viewButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#111827",
    borderRadius: 8,
    padding: 8,
  },
  deleteButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#d92d20",
    borderRadius: 8,
    padding: 8,
  },
  startButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#12b76a",
    borderRadius: 8,
    padding: 8,
  },
  playMatchButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f59e0b",
    borderRadius: 8,
    padding: 8,
  },
  disabledDeleteButton: {
    backgroundColor: "#e27870",
  },
});

export const gameRosterScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  container: {
    flex: 1,
    width: "100%",
    maxWidth: 600,
    alignSelf: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#111827",
  },
  headerSubtitle: {
    fontSize: 16,
    color: "#4B5563",
    fontWeight: "600",
  },
  listContainer: {
    flexGrow: 1,
    gap: 12,
    paddingBottom: 24,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E5E7EB",
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardSelected: {
    borderColor: "#2563EB",
    backgroundColor: "#EFF6FF",
  },
  checkboxContainer: {
    marginRight: 16,
  },
  playerInfoContainer: {
    flex: 1,
  },
  playerHeader: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "600",
  },
  playerStats: {
    color: "#6B7280",
    fontSize: 14,
    marginTop: 4,
  },
  saveButton: {
    backgroundColor: "#2563EB",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 16,
    marginTop: 16,
  },
  saveButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyStateText: {
    color: "#6B7280",
    fontSize: 15,
  },
});

export const gamePlayMatchStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#111827",
  },
  container: {
    flex: 1,
    maxWidth: 600,
    alignSelf: "center",
    width: "100%",
  },
  header: {
    padding: 16,
    backgroundColor: "#1F2937",
    borderBottomWidth: 1,
    borderBottomColor: "#374151",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "stretch",
  },
  headerLeft: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  headerCenterCol: {
    flex: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  headerRight: {
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "flex-end",
  },
  teamName: {
    color: "#F9FAFB",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "left",
  },
  rivalName: {
    color: "#F9FAFB",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "right",
  },
  score: {
    color: "#FBBF24",
    fontSize: 24,
    fontWeight: "900",
  },
  quarterScoreText: {
    color: "#9CA3AF",
    fontSize: 14,
    fontWeight: "600",
    marginVertical: 4,
  },
  timeText: {
    color: "#EF4444",
    fontSize: 28,
    fontWeight: "bold",
    fontVariant: ["tabular-nums"],
  },
  playPauseButton: {
    padding: 8,
    backgroundColor: "#374151",
    borderRadius: 8,
  },
  benchContainer: {
    padding: 6,
    backgroundColor: "#1F2937",
    borderBottomWidth: 1,
    borderBottomColor: "#374151",
    gap: 6,
  },
  quartersRow: {
    flexDirection: "row",
    justifyContent: "center",
  },
  quarterButton: {
    backgroundColor: "#374151",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginHorizontal: 2,
  },
  quarterButtonActive: {
    backgroundColor: "#2563EB",
  },
  quarterButtonText: {
    color: "#D1D5DB",
    fontWeight: "bold",
    fontSize: 12,
  },
  quarterButtonTextActive: {
    color: "#FFF",
  },
  actionButtonsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 4,
  },
  benchPlayersRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 4,
  },
  jerseyToken: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  jerseyTokenSelected: {
    transform: [{ scale: 1.15 }],
  },
  jerseyNumber: {
    position: "absolute",
    color: "#FFF",
    fontWeight: "900",
    fontSize: 14,
    zIndex: 10,
    top: 10,
  },
  subButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: "#374151",
    alignItems: "center",
    justifyContent: "center",
  },
  subButtonActive: {
    backgroundColor: "#DC2626",
  },
  subButtonText: {
    color: "#F9FAFB",
    fontWeight: "bold",
    fontSize: 12,
  },
  courtContainer: {
    flex: 1,
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  playerToken: {
    position: "absolute",
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
  },
  playerTokenText: {
    position: "absolute",
    color: "#FFF",
    fontWeight: "900",
    fontSize: 16,
    zIndex: 10,
    top: 15,
  },
  toolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    padding: 6,
    backgroundColor: "#1F2937",
    gap: 4,
  },
  statButton: {
    backgroundColor: "#374151",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  statButtonDisabled: {
    opacity: 0.5,
  },
  statButtonText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 12,
  },
  toolButton: {
    backgroundColor: "#374151",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    width: "31%",
    alignItems: "center",
  },
  toolButtonPoint: {
    backgroundColor: "#059669",
  },
  toolButtonMiss: {
    backgroundColor: "#DC2626",
  },
  toolButtonText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#1F2937",
    borderRadius: 16,
    padding: 24,
    width: "100%",
    maxWidth: 400,
  },
  modalTitle: {
    color: "#F9FAFB",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 8,
    textAlign: "center",
  },
  modalPlayerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#374151",
  },
  modalPlayerName: {
    color: "#F9FAFB",
    fontSize: 16,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 24,
  },
  modalButtonCancel: {
    flex: 1,
    padding: 14,
    backgroundColor: "#374151",
    borderRadius: 8,
    marginRight: 8,
    alignItems: "center",
  },
  modalButtonConfirm: {
    flex: 1,
    padding: 14,
    backgroundColor: "#3B82F6",
    borderRadius: 8,
    marginLeft: 8,
    alignItems: "center",
  },
  modalButtonCancelText: {
    color: "#D1D5DB",
    fontWeight: "bold",
  },
  modalButtonConfirmText: {
    color: "#FFF",
    fontWeight: "bold",
  },
  toastContainer: {
    position: "absolute",
    bottom: 80,
    left: 20,
    right: 20,
    backgroundColor: "#EF4444",
    padding: 12,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
    zIndex: 999,
  },
  toastText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 14,
    flex: 1,
  },
  statsHeader: {
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#374151"
  },
  statsPlayerName: {
    color: "#FFF",
    fontSize: 20,
    fontWeight: "800",
  },
  statsCenterRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 20,
    backgroundColor: "#1F2937",
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#374151"
  },
  statsCenterBox: {
    alignItems: "center",
  },
  statsCenterLabel: {
    color: "#9CA3AF",
    fontSize: 12,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  statsCenterValue: {
    color: "#3B82F6",
    fontSize: 24,
    fontWeight: "900",
  },
  statsRowGroup: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    gap: 8,
  },
  statsBox: {
    flex: 1,
    backgroundColor: "#1F2937",
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#374151",
  },
  statsBoxTitle: {
    color: "#9CA3AF",
    fontSize: 11,
    textTransform: "uppercase",
    marginBottom: 8,
    fontWeight: "600",
  },
  statsBoxValue: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  statsBoxSub: {
    color: "#9CA3AF",
    fontSize: 12,
    marginTop: 4,
    fontWeight: "bold"
  }
});
