export async function createTrainings(TrainingsModel) {
  await TrainingsModel.create({
    team_id: 1,
    training_number: 1,
    date: "24/09/2025",
    warmup1: "Rotación Articular",
    warmup1_explanation: "warmup1_explanation",
    warmup2: "Circuito defensivo",
    warmup2_explanation: "Circuito completo",
    warmup3: "Trenza",
    warmup3_explanation: "warmup3_explanation",
    exercise1: "Ejercicio 1",
    exercise1_explanation: "exercise1_explanation",
    exercise2: "exercise2",
    exercise2_explanation: "exercise2_explanation",
    exercise3: "exercise3",
    exercise3_explanation: "exercise3_explanation",
    exercise4: "exercise4",
    exercise4_explanation: "exercise4_explanation",
    exercise5: "exercise5",
    exercise5_explanation: "exercise5_explanation",
    exercise6: "exercise6",
    exercise6_explanation: "exercise6_explanation",
    cooldown1: "cooldown1",
    cooldown1_explanation: "cooldown1_explanation",
    cooldown2: "cooldown2",
    cooldown2_explanation: "cooldown2_explanation",
  });
}
