export default {
  GO_BACK: "GO_BACK",
  ADD_NEW_TEAM: "ADD_NEW_TEAM",
  MAIN: "MAIN",
  PLAYERS: "PLAYERS",
  CALENDAR: "CALENDAR",
  TRAININGS: "TRAININGS",
  GAMES: "GAMES",
  EDIT_TEAM: "EDIT_TEAM",
  ADD_NEW_PLAYER: "ADD_NEW_PLAYER",
  ADD_NEW_SESSION: "ADD_NEW_SESSION",
  SAVE: "SAVE",
  CREATE: "CREATE",
};
