export default {
  GO_BACK: "back",
  CLOSE_SESION: "door-open",
  ADD_NEW_TEAM: "add-moderator",
  MAIN: "MAIN",
  PLAYERS: "users",
  CALENDAR: "calendar",
  TRAININGS: "clipboard",
  GAMES: "basketball-hoop-outline",
  EDIT_TEAM: "settings",
  ADD_NEW_PLAYER: "add-user",
  ADD_NEW_SESSION: "assignment-add",
  ADD_NEW_GAME: "basketball",
  SAVE: "save",
  CREATE: "CREATE",
  ROTATE_SCREEN: "screen-rotation",
};
